{
 "title": "Ad Engine Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Суммарное количество показов за минуту",
   "type": "timeseries",
   "description": "График суммарного количество показов за минуту по всем компаниям",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ad_engine:impressions_per_minute",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Суммарный Доход платформы",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ad_engine:total_revenue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Доход от кликов на рекламу",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ad_engine:revenue_from_clicks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Суммарное количество кликов на рекламы за минуту",
   "type": "timeseries",
   "description": "График суммарное количество кликов на рекламы за минуту по всем компаниям",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
   "targets": [
    { "expr": "ad_engine:clicks_per_minute", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Доход за показы рекламы",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ad_engine:revenue_from_impressions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "График дохода за минуту",
   "type": "barchart",
   "description": "График дохода за показы, клики и общий доход за минуту",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ad_engine:minute_revenue_from_clicks",
     "legendFormat": "__auto"
    },
    {
     "expr": "ad_engine:minute_revenue_from_impressions",
     "legendFormat": "__auto"
    },
    { "expr": "ad_engine:minute_total_revenue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество ошибок API за минуту",
   "type": "timeseries",
   "description": "Суммарное количество ошибок API (500) за минуту",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "expr": "ad_engine:api_errors_per_minute",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Отношение кликов к показам (CTR)",
   "type": "piechart",
   "description": "График отношения кликов к показам (CTR)",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ad_engine:ctr_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Прирост дохода за минуту",
   "type": "timeseries",
   "description": "Тренд прироста дохода за минуту",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 21 },
   "targets": [
    { "expr": "ad_engine:trend_revenue", "legendFormat": "__auto" }
   ]
  }
 ]
}