global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - recording_rules.yml

scrape_configs:
  - job_name: 'ad_engine_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8080']
