"""Initial migration

Revision ID: 22a2507bee8d
Revises: 8bfb6b2a03c8
Create Date: 2025-02-20 19:14:39.948614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a2507bee8d'
down_revision: Union[str, None] = '8bfb6b2a03c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
