"""Initial migration

Revision ID: 6fd8ae09b12c
Revises: 22a2507bee8d
Create Date: 2025-02-20 19:16:51.154044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd8ae09b12c'
down_revision: Union[str, None] = '22a2507bee8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'cost_per_impression',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('campaigns', 'cost_per_click',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'cost_per_click',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('campaigns', 'cost_per_impression',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
