"""Initial migration

Revision ID: c4d20835e6c3
Revises: d03feb2f7c56
Create Date: 2025-02-12 15:36:19.402673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d20835e6c3'
down_revision: Union[str, None] = 'd03feb2f7c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('advertiser_id', sa.UUID(), nullable=False),
    sa.Column('impressions_limit', sa.Integer(), nullable=False),
    sa.Column('clicks_limit', sa.Integer(), nullable=False),
    sa.Column('cost_per_impression', sa.Float(), nullable=False),
    sa.Column('cost_per_click', sa.Float(), nullable=False),
    sa.Column('ad_title', sa.String(), nullable=False),
    sa.Column('ad_text', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('targeting', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.advertiser_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
