"""Initial migration

Revision ID: cbc9c68330aa
Revises: c4d20835e6c3
Create Date: 2025-02-12 15:59:18.162842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc9c68330aa'
down_revision: Union[str, None] = 'c4d20835e6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('start_day', sa.Integer(), nullable=False))
    op.add_column('campaigns', sa.Column('end_day', sa.Integer(), nullable=False))
    op.drop_column('campaigns', 'start_date')
    op.drop_column('campaigns', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('campaigns', 'end_day')
    op.drop_column('campaigns', 'start_day')
    # ### end Alembic commands ###
