"""Initial migration

Revision ID: dcf620a74ea9
Revises: cbc9c68330aa
Create Date: 2025-02-14 13:38:54.957649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf620a74ea9'
down_revision: Union[str, None] = 'cbc9c68330aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'image_url')
    # ### end Alembic commands ###
