"""Initial migration

Revision ID: e02d16145c13
Revises: cab5662317c4
Create Date: 2025-02-20 23:41:54.989725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02d16145c13'
down_revision: Union[str, None] = 'cab5662317c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('start_date', sa.Integer(), nullable=False))
    op.add_column('campaigns', sa.Column('end_date', sa.Integer(), nullable=False))
    op.drop_column('campaigns', 'end_day')
    op.drop_column('campaigns', 'start_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('start_day', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('end_day', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('campaigns', 'end_date')
    op.drop_column('campaigns', 'start_date')
    # ### end Alembic commands ###
